/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        notion: {
          bg: 'var(--notion-bg)',
          'bg-secondary': 'var(--notion-bg-secondary)',
          'bg-tertiary': 'var(--notion-bg-tertiary)',
          text: 'var(--notion-text)',
          'text-secondary': 'var(--notion-text-secondary)',
          border: 'var(--notion-border)',
          blue: 'var(--notion-blue)',
          'blue-bg': 'var(--notion-blue-bg)',
          green: 'var(--notion-green)',
          'green-bg': 'var(--notion-green-bg)',
          orange: 'var(--notion-orange)',
          'orange-bg': 'var(--notion-orange-bg)',
          red: 'var(--notion-red)',
          'red-bg': 'var(--notion-red-bg)',
          purple: 'var(--notion-purple)',
          'purple-bg': 'var(--notion-purple-bg)',
        },
        primary: {
          50: '#f0f4f8',
          100: '#d9e2ec',
          200: '#bcccdc',
          300: '#9fb3c8',
          400: '#829ab1',
          500: '#627d98',
          600: '#486581',
          700: '#334e68',
          800: '#243b53',
          900: '#102a43',
          950: '#0a1929',
        },
        danger: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
      },
      fontFamily: {
        sans: ['System', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
